version: '3.3' 
services:
  mysql-db: 
    image: mysql:latest
    restart: always
    container_name: mysql-db
    networks:
      - appnetwork
    environment: 
      MYSQL_DATABASE: "acit3495"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "2705895a"
      MYSQL_ROOT_PASSWORD: "2705895a"
    ports: 
      - "3306:3306"
    volumes: 
      - mysql-data:/var/lib/mysql
  mongo-db: 
    image: mongo:latest
    restart: always
    container_name: mongo-db
    networks:
      - appnetwork
    ports: 
      - "27017:27017"
    volumes: 
      - mongo-data:/data/db
  analytics:
    image: ijazhussain/analytics
    restart: always
    container_name: analytics
    networks:
      - appnetwork
    ports:
      - "8090:8090"
    depends_on:
      - "mysql-db"
      - "mongo-db"
  auth:
    image: ijazhussain/auth
    restart: always
    container_name: auth
    networks:
      - appnetwork
    ports:
      - "8080:8080"
    depends_on:
      - "enter"
      - "show"
  enter:
    image: ijazhussain/enter
    restart: always
    container_name: enter
    networks:
      - appnetwork
    ports:
      - "8100:8100"
    depends_on:
      - "mysql-db"
  show:
    image: show
    restart: always
    container_name: ijazhussain/show
    networks:
      - appnetwork
    ports:
      - "8200:8200"
    depends_on:
      - "mongo-db"
volumes: 
  mysql-data:
  mongo-data: